### PR TITLE
add user autocmd for checkout

### PR DESCRIPTION
**Pull request by mckellygit**
Hi,
ty for vim-twiggy.
A simple User autocmd called on checkout.
I used it to update vimagit when I change branches.
thx,
-m

### CODE REVIEW

**Review by sodapopcan — CHANGES_REQUESTED** [review]
Hey, thanks for the PR!

Happy to merge but please:
  - Lose the comments
  - Lose the `Command` suffix as it doesn't add anything.  `TwiggyCheckout` is clear enough as a `User` command.

Additionally, if you could, please document this.  After the `MAPPINGS` section, adding the following will suffice:

```viml
AUTOCOMMANDS                                    *twiggy-autocommands*

                                                *User_TwiggyCheckout*
TwiggyCheckout          After checking out a branch.

```

Thanks again!

**Comment by mckellygit** [comment]
ok, I've updated PR.  Because it was small changes I just amended the original commit.
thx,
-m

**Comment by sodapopcan** [comment]
Sorry for the delay.  Thanks for your contribution!!

**Comment by mckellygit** [comment]
Awesome, thanks.

**Pull request merged**
